#============================================================================================================================|
# ___________.__  __
# \_   _____/|__|/  |_________
#  |    __)  |  \   __\___   /
#  |     \   |  ||  |  /    /
#  \___  /   |__||__| /_____ \
#      \/                   \/
#============================================================================================================================|
#
# Plugin Version: 1.0.1
# Author's Discord: Morphie#6969
#
#============================================================================================================================|

# The Discord Bot User Token. (Create a bot at - https://discordapp.com/developers/applications)
Token: 'MzYwNzgzNzkzNjQ2MjA2OTg2.DxmLNQ.RyPJ_gSOoFyCIuROFHCFas65iFQ'

# The ID of the channel relaying minecraft chat.
BridgeChannelID: '430497317531942912'

# The ID of the channel displaying join and leave messages.
JoinLeaveChannelID: '445625045667020800'

# How the messages will appear in the discord relay channel.
MinecraftToDiscordFormat: '**[**RANK**]** *PLAYER* **>** MESSAGE'

# How the messages will appear in the minecraft chat when sent from the discord channel.
DiscordToMinecraftFormat: '&8[&bD&8] &eUSER &8&l> &fMESSAGE'

# Message sent when the bot is loaded.
BotLoaded: ':ballot_box_with_check: **Server Started.**'

# Message sent when the bot is unloaded.
BotUnloaded: ':redx: **Server Shutdown.**'

# Role colors for discord bridge
owner: "AA0000"
admin: "FF5555"
developer: "55FF55"
build-admin: "FFAA00"
operator: "00AAAA"
moderator: "55FFFF"
t-mod: "55FFFF"
builder: "FFFF55"
veteran: "FF55FF"