#============================================================================================================================|
# ___________.__  __
# \_   _____/|__|/  |_________
#  |    __)  |  \   __\___   /
#  |     \   |  ||  |  /    /
#  \___  /   |__||__| /_____ \
#      \/                   \/
#============================================================================================================================|
#
# Author's Discord: Morphie#6969
#
#============================================================================================================================|

# Bot Settings:
# The Discord Bot User Token. (Create a bot at - https://discordapp.com/developers/applications)
Token: "MzYwNzgzNzkzNjQ2MjA2OTg2.WcUUFw.mu3ME_Fr26bLDgfh0Kbe6CfQgI4"
# What the bots status is within the discord member list. Types: PLAYING, WATCHING, STREAMING
StatusMessage: "on SMPULTD.GG"

#============================================================================================================================|

# Discord Guild + Channel ID's
# The ID of the discord server Fitz is currently using.
Guild: "786248213845377045"
# The ID of the channel relaying minecraft chat.
BridgeChannelID: '930165288912175238'
# The ID of the channel displaying join and leave messages.
JoinLeaveChannelID: '951595979243671592'
# The ID of the information channel. (Server Information)
InformationChannelID: '802484042233675777'
# The ID of the rules channel.
RulesChannelID: '859972898599862343'
# The ID of the bot commands channel.
BotCommandsChannelID: '786248214407938052'
# The ID of the bot commands channel.
StaffChatChannelID: '786248215535812647'

#============================================================================================================================|

#Message Formats
# How the messages will appear in the discord bridge channel.
MinecraftToDiscordFormat: '**[**%RANK%**]** *%PLAYER%* **»** '
# How the messages will appear in the minecraft chat when sent from the discord channel.
DiscordToMinecraftFormat: '&8[&bD&8] &e%vault_rankprefix%%essentials_nickname% &8» &fMESSAGE'
# Format for the bridge channel topic.
BridgeTopicFormat: '[:satellite:] **TIME** **|** **Unique Joins:** *JOINS* **|** **Players:** *PLAYERS*'
# Message sent when the bot is loaded.
BotLoaded: ':ballot_box_with_check: **Server Started.**'
# Message sent when the bot is unloaded.
BotUnloaded: ':no_entry: **Server Shutdown.**'
# Message sent in discord bridge when a player joins the server for the first time.
PlayerFirstJoin: '[:piñata:] %FITZ% **»** ***%PLAYER%*** *has joined the server for the first time!*'
# Message sent in discord bridge when a player joins the server.
PlayerJoin: '[:green_circle:] %PLAYER% connected.'
# Message sent in discord bridge when a player leaves the server.
PlayerLeave: '[:red_circle:] %PLAYER% disconnected.'
# Message sent in discord bridge when a player dies in game.
PlayerDeathMessage: ':coffin: ***%PLAYER%*** *DEATH_MESSAGE*'

#============================================================================================================================|

# Default Embed Settings: (Things for the fancy messages fitz can make!)
# Imgur Link of logo
Image: 'https://i.imgur.com/NlmYZ9K.png'
# Title or default header of each embeded message.
Header: 'SMPULTD.GG » TITLE'
# Footer of each embeded message.
Footer: 'All rights reserved, SMPULTD.GG 2023 ↠'
# Outline color of the embeded messages. (Hex Code)
Color: '#00AA00'

#============================================================================================================================|

# Roles Settings:
# Role given to users when they join the discord server
JoinRole: "► Member"
# Role given to users that successfully link their MC and Discord accounts
VerifiedID: "945395204360376340"
# Admin Role given to fitz for his naming
FitzID: "904803521755500554"

#============================================================================================================================|

# Role colors for discord bridge
Owner: "AA0000"
Admin: "5555FF"
Operator: "00AAAA"
Moderator: "55FFFF"
Helper: "55FF55"
Zeus: "00AA00"
Poseidon: "00AA00"
Hades: "00AA00"
Ares: "00AA00"
Athena: "00AA00"
Apollo: "00AA00"