name: Fitz
version: 1.3-ALPHA
main: com.salvos.morphie.fitz.Fitz
author: Morphie
api-version: 1.18
depend: [Vault, PlaceholderAPI]
commands:
  discord:
    description: Main command for the in-game.
    usage: /<command>
    aliases: [fitz]