name: Fitz
version: 1.3-ALPHA
main: com.salvos.morphie.fitz.Fitz
author: Morphie
api-version: 1.13
depend: [Vault]
commands:
  discord:
    description: Main command for the in-game.
    usage: /<command>
    aliases: [fitz]
  verify:
    description: Main command to verify discord account.
    usage: /<command>
    aliases: [dv]